/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const addresses_Logic_Before_Insert_Update = require('./code/addresses-logic-before-insert-update');

class cap_rest_serviceSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Addresses', async (request) => {
            await addresses_Logic_Before_Insert_Update(request);
        });

        return super.init();
    }
}


module.exports = {
    cap_rest_serviceSrv
};