/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const updateendereco_Logic = require('./code/updateendereco-logic');

class cap_rest_serviceSrv extends LCAPApplicationService {
    async init() {

        this.on('updateEndereco', async (request) => {
            return updateendereco_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    cap_rest_serviceSrv
};